name: Deploy to AWS (CDK)

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run: { working-directory: ./infra/ }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          node-version: 18
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ "us-west-2" }}
          role-to-assume: arn:aws:iam::763671682715:role/GitHubAction-PicklePower
      - name: Install CDK dependencies
        run: npm ci
      - name: Deploy CDK stack
        run: npx cdk deploy --require-approval never